### ISSUE TITLE
no png file found for pinout

### ISSUE THREAD

**Issue by devsoft-co-za** [sidharthmohannair/Tutorial-ESP32-C3-Super-Mini#1]
the link doesn't point to anything, is there a pinout available? Super useful guide otherwise - reminded me to update my boards

**Comment by sidharthmohannair** [comment]
Thank you for bringing this to our attention! I've resolved the issue, and the link should now point to the correct resource. A pinout is available, and I've updated the guide accordingly. I'm glad you found the guide useful, and I appreciate your reminder to update your boards.

If you have any other questions or feedback, feel free to reach out!
