### ISSUE TITLE
Pinout pictures incorrect

### ISSUE THREAD

**Issue by randy197** [sidharthmohannair/Tutorial-ESP32-C3-Super-Mini#3]
The two pinout pictures shown don't match each other.  Take note of the position of MISO and MOSI for example.

**Comment by sidharthmohannair** [comment]
Thank you for pointing this out! I’ve reviewed the pinout pictures and noticed the discrepancy you mentioned. I'll update the documentation with corrected images to ensure accuracy.

Please feel free to check back soon, and let me know if you spot anything else.
